---
- name: Create restic user
  become: true
  ansible.builtin.user:
    name: "{{ restic_user }}"
    shell: "/sbin/nologin"
    system: true
  when:
    - restic_create_user | bool
    - restic_user != 'root'
